x=int(input("Enter the first number in series is "))
y=int(input("Enter the last number in series is "))
numbers=list(range(x,y+1))
even=list(filter(lambda x:x%2==0,numbers))
odd=list(filter(lambda x:x%2!=0,numbers))
print(f"Number  of even numbers is {len(even)}" )
print(f"Number of odd numbers is {len(odd)}" )
